theme: jekyll-theme-minimal
title: Simple Cornish Map
description: This website demonstrates how to easily publish and display an interactive map made with Folium.
logo: Logo_IUT_SD_Carcassonne.jpg